name: app_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  audioplayers: ^6.5.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  flutter_reactive_ble: ^5.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_animate: ^4.5.0
  video_player: ^2.8.1  
  chewie: ^1.7.4   
  syncfusion_flutter_gauges: ^25.1.35  
  url_launcher: ^6.3.2
  audioplayers: ^6.5.0


flutter:
  uses-material-design: true
  assets:
    - lib/assets/robot.png
    - lib/assets/logo1.png
    - lib/assets/gemini_data.json
    - lib/assets/audio/audio1.wav
    - lib/assets/audio/audio2.wav
    - lib/assets/audio/audio3.wav
    - lib/assets/audio/audio4.wav
    - lib/assets/audio/audio5.wav

  fonts:
    - family: AGRESSIVE
      fonts:
        - asset: lib/assets/fonts/AGRESSIVE.otf
    - family: Lokeya
      fonts:
        - asset: lib/assets/fonts/Lokeya.ttf
          
    
    